name: Build

on: push

# 在全域加入這個環境變數
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: 'true'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20' # 這裡是你專案本身的 Node 版本，跟 Actions 執行環境不衝突
          
      # 你的其他步驟...
